### ISSUE TITLE
problem make python3-pip

### ISSUE THREAD

**Issue by tyriis** [NucleaPeon/OpenWRT-Python3-Utils#1] opened 2015-08-01 12:19 UTC
when i run the make command it stops withe the following message.

$ make package/python3-pip
...
**\* No rule to make target `package/python3-pip'.  Stop.
...

and

$make
...
Traceback (most recent call last):
  File "./setup.py", line 6, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
make[3]: **\* [/home/user/openwrt/trunk/build_dir/target-mips_34kc_musl-1.1.10/pip-7.0.3/.built] Error 1
make[3]: Leaving directory `/home/user/openwrt/trunk/feeds/pip/python3-pip'
make[2]: *** [package/feeds/pip/python3-pip/compile] Error 2
make[2]: Leaving directory`/home/user/openwrt/trunk'
make[1]: **\* [/home/user/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.10/stamp/.package_compile] Error 2
...

**Comment by NucleaPeon** [comment] 2015-08-01 20:00
`ImportError: No module named 'setuptools'` <-- that is your problem. When you select python3-pip to install, does it also select python3-setuptools? It is a dependency of pip.

**Comment by tyriis** [comment] 2015-08-02 10:34
yes it does.

$ ./scripts/feeds install python3-pip
Installing package 'python3-pip' from pip
Installing package 'python3-setuptools' from pip

**Comment by NucleaPeon** [comment] 2015-08-02 16:53
Are you installing them as modules or built-in? 

**Some background info you may already know:**

Setuptools is used for building python packages, it has no real effect on an OpenWRT system because it doesn't include python-dev, a neccesssity when building the software. Having a missing setuptools library likely refers to it not being built or placed in the proper place in the build or staging directory.

When you build your package, can you tell me if there are any setuptools files found in your `$(STAGING_DIR)$(PYTHON3_PKG_DIR)` folder? It should be something like: `/some/path/staging_arch/usr/lib/python3.4/site-packages/`

I can try rebuilding the buildroot on my machine. Please post both your kernel configuration (`config-3.xx`) and your `.config` file so I can reproduce with your setup. If you have additional feeds, please post those unless your setup contains sensitive or private info. (pastebin or attaching files to this issue)

**Comment by tyriis** [comment] 2015-08-02 21:36
> Are you installing them as modules or built-in?

i install them as modules not build-in

> Setuptools is used for building python packages, it has no real effect on an OpenWRT system because it doesn't include python-dev, a neccesssity when building the software. Having a missing setuptools library likely refers to it not being built or placed in the proper place in the build or staging directory.

what does this mean? is there no possibility t create a python3-dev package for OpenWRT or it is just not included?

> When you build your package, can you tell me if there are any setuptools files found in your $(STAGING_DIR)$(PYTHON3_PKG_DIR) folder? It should be something like: /some/path/staging_arch/usr/lib/python3.4/site-packages/

i have 3 folders in the staging_dir:
- host/lib/python3.4/site-packages (only the README)
- target-mips_34kc_musl-1.1.10/usr/lib/python3.4/site-packages (only the README)
- toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10 (no python3.4 folder)

> I can try rebuilding the buildroot on my machine. Please post both your kernel configuration (config-3.xx) and your .config file so I can reproduce with your setup. If you have additional feeds, please post those unless your setup contains sensitive or private info. (pastebin or attaching files to this issue)

[feeds.conf.default](http://pastebin.com/j5dcKd6m)
[.config](http://pastebin.com/tCCX7STQ)
[config-3.13.0-55-generic](http://pastebin.com/KRmhsFRJ)

thanks a lot for your help

**Comment by NucleaPeon** [comment] 2015-08-02 23:26
I'll take a look at your configs later. 

I, for now, would try compiling in all your python3-\* packages `[*]` instead of as modules. Try that and see if it helps, but you may have to remove your build_dir or `make clean` before you attempt to do so.

As for including python-dev libs, allow me to explain. 

OpenWRT as a product does not include 
a) development tools
b) gcc/c++/any compilers on the completed image
c) development libraries.

This is because OpenWRT is meant to be deployed on routers, embedded devices, and all manner of computers with very low storage space, ram and processor speed.

When someone uses `setuptools` to install a python package, it **compiles** any libraries associated with it and then compiles the python into bytecode. 

```
 it **compiles** any libraries associated with it
```

Compilation as a whole uses a lot of memory and can do a lot of writes to storage. This is a bad idea for any embedded system, so things such as python development files, libraries and compilers are just not available on the resulting system. When you utilize a program like `pip`, it downloads and compiles a program using setuptools. It's important for you to understand that 

**pip and setuptools cannot be used on a router. Pip and setuptools can only be used on your buildroot to download python software and compile it for your image.**

That is why my feed includes such things as `python3-tornado` and `python3-paramiko`. They are downloaded via pip and installed via setuptools, but this is all done on the build and staging portions of the image build. If you want to use pip on OpenWRT, you need to include the python development files, something I have not done. If you want to include software like tornado and paramiko without having to fudge around with the source code and use a simpler distribution tool to pull and install the programs, compile in setuptools and pip, write up a makefile for the pip software that will download and install it to your staging dir, then have your makefile bundle it up into a package and persist it into the image you are creating.

I hope that clears the process up, OpenWRT documentation is not the easiest to understand. If you have a piece of software you want included on your image, tell me and I can try to build a `Makefile` for it.

Also, I see you are using the `musl` c library. I have not ever had success in using it to build an image, I use ulibc. Perhaps switching to that will help as well.

**Comment by tyriis** [comment] 2015-08-05 19:13
> pip and setuptools cannot be used on a router. Pip and setuptools can only be used on your buildroot to download python software and compile it for your image.
> 
> That is why my feed includes such things as python3-tornado and python3-paramiko. They are downloaded via pip and installed via setuptools, but this is all done on the build and staging portions of the image build. If you want to use pip on OpenWRT, you need to include the python development files, something I have not done. If you want to include software like tornado and paramiko without having to fudge around with the source code and use a simpler distribution tool to pull and install the programs, compile in setuptools and pip, write up a makefile for the pip software that will download and install it to your staging dir, then have your makefile bundle it up into a package and persist it into the image you are creating.

okay i think i understand the problem now

> I hope that clears the process up, OpenWRT documentation is not the easiest to understand. If you have a piece of software you want included on your image, tell me and I can try to build a Makefile for it.

this would be very lovely, but i need some more packages :/
- pyramid >= 1.4
- pyramid-debugtoolbar
- pyramid_tm
- pyramid_rpc
- waitress
- sqlalchemy_utils
- passlib
- docutils
- click
- networkx
- PyYAML
- SQLAlchemy >= 0.9
- zope.sqlalchemy >= 0.7
- jinja2 >= 2.7
- csscompressor >= 0.9
- libsass >= 0.4

give me a donation link to buy u a beer, i guess it will take some time and knowledge.

**Comment by NucleaPeon** [comment] 2015-08-12 20:17
Over the past few days I've been trying to compile according to your specs. I think the MIPS architecture has some issue with python3-pycrypto, so I wasn't able to build an image. I've tried across a couple virtual machines and on Gentoo. I've decided to focus on the packages instead, though some are rather complicated like `libsass`, which is giving me issues due to compiler options or something.

I'll close this bug, but on the README.md I will list packages and check them off as they are completed.

I don't have a donation link or anything, but your testing them is helping me out so it's all good :)

**Closed as completed by NucleaPeon** 2015-08-12 20:17 UTC
